# Generated by Django 4.2.5 on 2023-11-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_database1_delete_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='database1',
        ),
    ]
